### ISSUE TITLE
Do not allow submission of two medications with same cabinet ID

### ISSUE THREAD

**Issue by gvillarruz** [gvillarruz/RxMind-App#11]
Read from cabinet ids and if it already exists, add error notification

**Comment by gvillarruz** [comment]
https://www.w3schools.com/jsref/jsref_includes_array.asp

**Comment by harkirangrewal** [comment]
Create a list of cabinet ids already being used, and check the list when a new medication is trying to be added 
Also remove the cabinetid from the list when a medication is removed

- If the cabinetid is the same as that in the list, break the function and use the messaging service to display an error to the user

**Comment by gvillarruz** [comment]
to remove one https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

**Comment by harkirangrewal** [comment]
Fixed in [138bb25](https://github.com/gvillarruz/RxMind-App/commit/138bb254adf1dbf7264f251197d9445f9cebac71)
